baseURL = "https://www.leonidboykov.com/"
copyright = "Copyright &copy; {year} Leonid Boykov"
disqusShortname = "leonidboykov"
languageCode = "en"
pygmentsCodeFences = true
pygmentsOptions = "nobackground=false"
pygmentsStyle = "friendly"
theme = "mercy"
title = "Leonid Boykov"
[[menu.main]]
name = "Projects"
url = "/project/"
weight = 3
[[menu.main]]
name = "Blog"
url = "/post/"
weight = 2
[[menu.social]]
name = "gitlab"
url = "https://gitlab.com/leonidboykov/"
weight = 3
[[menu.social]]
name = "github"
url = "https://github.com/leonidboykov/"
weight = 2
[[menu.social]]
name = "twitter"
url = "https://twitter.com/leonidboykov/"
weight = 1
[params]
bitbucketusername = "leonidboykov"
githubusername = "leonidboykov"
gitlabusername = "leonidboykov"
[social]
twitter = "leonidboykov"
