baseURL = "https://leonidboykov.com/"
languageCode = "en"

title = "Leonid Boykov"
theme = "mercy"

copyright = "Copyright &copy; {year} Leonid Boykov"

pygmentsCodeFences = true
pygmentsStyle = "dracula"
pygmentsOptions = "nobackground=false"

disqusShortname = "leonidboykov"

[social]
  twitter = "leonidboykov"

[params]
  subTitle = "Hobbyist Programmer"
  favicon = "/uploads/favicon-256.png"

  github = "leonidboykov"
  gitlab = "leonidboykov"
  bitbucket = "leonidboykov"

[[menu.main]]
  url = "/post/"
  name = "Blog"
  weight = 2

[[menu.social]]
  url = "https://twitter.com/leonidboykov/"
  name = "twitter"
  weight = 1
[[menu.social]]
  url = "https://github.com/leonidboykov/"
  name = "github"
  weight = 2
[[menu.social]]
  url = "https://gitlab.com/leonidboykov/"
  name = "gitlab"
  weight = 3
