baseURL = "https://www.leonidboykov.com/"
languageCode = "en-us"
title = "Leonid Boykov"
theme = "minimal"
disqusShortname = "leonidboykov"


[params]
  copyright = "Copyright &copy; 2017 Leonid Boykov. Powered by [Hugo](https://gohugo.io) and [Minimal](https://github.com/calintat/minimal)"
  author = "Leonid Boykov"
  description = "Blogger &bull; Programmer &bull; Gopher"
  githubUsername = "leonidboykov"
  accent = "#2F4050"
  showBorder = true
  backgroundColor = "white"
  font = "Varela Round"
  pygmentsCodeFences = true
  pygmentsStyle = "friendly"
  # line numbers are selectable, turn off for now
  pygmentsOptions = "linenos=false"

  # disable highlight in favour of new chroma highlighter
  highlight = false
  # highlightStyle = "magula"
  # highlightLanguages = ["go", "yaml"]


[[menu.main]]
  url = "/"
  name = "Home"
  weight = 1

[[menu.main]]
  url = "/post/"
  name = "Posts"
  weight = 2

[[menu.main]]
  url = "/project/"
  name = "Projects"
  weight = 3

[[menu.main]]
  url = "/about/"
  name = "About"
  weight = 4

[[menu.icon]]
  url = "https://twitter.com/leonidboykov/"
  name = "twitter"
  weight = 1

[[menu.icon]]
  url = "https://github.com/leonidboykov/"
  name = "github"
  weight = 2

[[menu.icon]]
  url = "https://gitlab.com/leonidboykov/"
  name = "gitlab"
  weight = 3
