[build]
  publish = "public"
  command = "hugo --minify"

[context.production.environment]
  HUGO_VERSION = "0.48"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
    HUGO_VERSION = "0.48"

[context.branch-deploy]
  command = "hugo --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

  [context.branch-deploy.environment]
    HUGO_VERSION = "0.48"

[[redirects]]
  from = "https://leonidboykov.netlify.com/*"
  to = "https://leonidboykov.com/:splat"
  status = 301
  force = true
