[build]
  publish = "public"
  command = "hugo"

[context.production]
  command = "hugo"

  [context.production.environment]
    HUGO_VERSION = "0.36.1"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

  [context.deploy-preview.environment]
    HUGO_VERSION = "0.36.1"
