---
label: project
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: repo
  label: Repo
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: type
  label: Type
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: weight
  label: Weight
  type: text
  hidden: false
  default: 0
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/project/hugo-scientific-theme.md
- content/project/grav-theme-ibraintech.md
